name: Build & Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - "producer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/demo-queue-it/queue-producer:latest ./producer
          docker push ghcr.io/${{ github.actor }}/demo-queue-it/queue-producer:latest