name: Build & Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - "producer/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/queue-producer:latest ./producer
          docker push ghcr.io/${{ github.actor }}/queue-producer:latest