name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        env:
          TF_VAR_linode_token: ${{ secrets.LINODE_TOKEN }}  # Pass Linode token as an environment variable
        run: |
          cd iac/
          terraform init
          terraform plan
          terraform apply -auto-approve